#!/bin/sh
cd ${0%/*} || exit 1
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions
cd laminar && cleanCase && rm -rf VTK postProcessing && cd ..
cd turbulento && cleanCase && rm -rf VTK postProcessing && cd ..
